import json
import numpy as np
from pathlib import Path
from scipy.stats import triang
from typing import Dict, Tuple
from distributions_vulnerabilities import distributions_vulnerabilities
from build_vulnerabilities_matrices import build_matrices
from plot_simulated_histograms import plot_simulated_histograms
from plot_ranking_risks import plot_ranking_risks

def _create_triangular_distribution(param: Dict[str, int]):
    a, c, b = param["min"], param["mode"], param["max"]
    if b == a:                  # degenerates (all the same) → uses delta dirac
        return lambda n: np.full(n, a)
    scale = b - a
    loc = a
    shape_c = (c - a) / scale   # mode position in [0,1]
    dist = triang(shape_c, loc=loc, scale=scale)
    return dist.rvs             # returns sampling function

def simulate_monte_carlo(parameters: Dict[str, Dict[str, int]], 
                         profiles: Dict[str, Dict[str, list]],
                         n_samples: int = 50000, 
                         seed: int | None = None) -> Tuple[Dict[str, np.ndarray], np.ndarray]:
    
    rng = np.random.default_rng(seed)
    np.random.seed(rng.integers(0, 2**32 - 1))  # compatibility with scipy
    
    samples: Dict[str, np.ndarray] = {}
    overall_risk = np.zeros(n_samples)
    
    levels = ["LOW", "MEDIUM", "HIGH", "CRITICAL", "UNKNOWN"]
    
    for level in levels:
        if level not in parameters:
            continue
            
        dist_func = _create_triangular_distribution(parameters[level])
        
        # 1. Draws the NUMBER of CVEs for each of the 50,000 rounds
        counts = np.round(dist_func(n_samples)).astype(int)
        counts[counts < 0] = 0 # if negatives
        samples[level] = counts
        
        total_cves = counts.sum()
        
        # 2. Randomly selects the QUALITY (CVSS and EPSS) for all generated CVEs
        if total_cves > 0 and level in profiles:
            cvss_pool = np.array(profiles[level].get("CVSS", []))
            epss_pool = np.array(profiles[level].get("EPSS", []))
            
            # Security fallback if the profile is empty (e.g., zero severity detected images)
            if len(cvss_pool) == 0: cvss_pool = np.array([0.0])
            if len(epss_pool) == 0: epss_pool = np.array([0.0])
            
            # Random selection with replacement (Bootstrap) based on real data
            drawn_cvss = rng.choice(cvss_pool, size=total_cves, replace=True)
            drawn_epss = rng.choice(epss_pool, size=total_cves, replace=True)
            
            # Individual risk of each fictitious CVE = CVSS * EPSS
            cve_risks = drawn_cvss * drawn_epss
            
            # 3. Grouping the sum of the risks back to the 50,000 instances
            sample_indices = np.repeat(np.arange(n_samples), counts)
            summed_risks = np.bincount(sample_indices, weights=cve_risks, minlength=n_samples)
            
            overall_risk += summed_risks

    return samples, overall_risk

def distribution_summary(arr: np.ndarray, label: str) -> None:
    print(f"\n📊 {label}")
    print(f"  Mean      : {arr.mean():.2f}")
    print(f"  Variance  : {arr.var():.2f}")
    print(f"  Std. Dev. : {arr.std():.2f}")
    print(f"  Min–Max   : {arr.min():.2f} – {arr.max():.2f}")

def main() -> None:
    # 1. Builds matrices to feed the triangular ones
    build_matrices()
    parameters = distributions_vulnerabilities("matrices.json")
    
    # 2. Loads the actual statistical profiles generated by the aggregator.
    profiles_path = Path("aggregated_summary/cvss_epss_profiles.json")
    if not profiles_path.exists():
        print("❌ Error: cvss_epss_profiles.json not found. Run vulnerabilities_aggregator.py first.")
        return
        
    with open(profiles_path, "r") as f:
        profiles = json.load(f)

    # 3. Simulation run
    n = 50_000  
    print(f"\n🎲 Starting Monte Carlo ({n} samples) with dynamic CVSS/EPSS profiles...")
    samples, overall_risk = simulate_monte_carlo(parameters, profiles, n)

    for level, arr in samples.items():
        distribution_summary(arr, f"{level} CVEs (Count)")

    distribution_summary(overall_risk, "EXPOSURE RISK (CVSS x EPSS)")
    
    # 4. Percentile Analysis of the Simulated Universe
    percentiles = np.percentile(overall_risk, [5, 25, 50, 75, 90, 95])
    print("\n📈 Percentiles of the Exposure Risk Distribution:")
    for p, val in zip([5, 25, 50, 75, 90, 95], percentiles):
        print(f"  {p:>2}%: {val:.2f}")

    # 5. Collection of Exact Real Risk
    estimated_risks_dict = {}
    summary_dir = Path("aggregated_summary")
    
    print("\n🔍 Estimated Risk Classification of Images:")
    for summary_file in summary_dir.rglob("summary.json"):
        with open(summary_file, "r") as f:
            data = json.load(f)
            img_name = data.get("image", "unknown").replace("trivy-scan:", "")
            estimated_risks = data.get("estimated_risk", 0.0)
            estimated_risks_dict[img_name] = estimated_risks
            
            if estimated_risks < percentiles[0]: tag = "🔵 Extremely Safe"
            elif estimated_risks < percentiles[3]: tag = "🟡 Moderate/Substantial"
            elif estimated_risks < percentiles[5]: tag = "🔴 High"
            else: tag = "❌ Critical"
            print(f"  {img_name.ljust(20)}: {estimated_risks:.2f} ({tag})")

    # 6. Generation of updated charts
    print("\n📉 Generating final charts...")
    plot_simulated_histograms(samples, overall_risk)
    
    Path("Plots").mkdir(exist_ok=True)
    plot_ranking_risks(estimated_risks_dict, output_path="Plots/ranking_exposure_risk.png")
    
    print("✅ Monte Carlo pipeline successfully completed!")

if __name__ == "__main__":
    main()